[general]
import = [
  "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[font]
normal = { family = "Inconsolata Nerd font" }
size = 14

# [terminal.shell]
# program = "/usr/local/bin/fish"
# args = ["--login"]
